@echo off
setlocal EnableDelayedExpansion

set "FORCE_OVERWRITE=0"
if /I "%FORCE%"=="1" set "FORCE_OVERWRITE=1"

:ParseArgs
if "%~1"=="" goto AfterArgs
if /I "%~1"=="--force" (
    set "FORCE_OVERWRITE=1"
    shift
    goto ParseArgs
)
echo ❌ Error: Unknown option %1
exit /b 1

:AfterArgs

REM KRAI Engine Docker Setup Script for Windows
REM Generates all required secrets from .env.example automatically
REM For production: Review and customize generated values before deployment
REM ============================================================================
REM NOTE: For Windows 10/11, we recommend using setup.ps1 (PowerShell) instead.
REM       setup.ps1 is shorter (299 vs. 744 lines), more maintainable, and uses
REM       modern .NET Crypto APIs for secure secret generation.
REM
REM       This batch script is provided as a legacy fallback for older Windows
REM       versions without PowerShell 5.0+.
REM
REM       To use PowerShell: .\setup.ps1
REM       To use Batch:      setup.bat
REM ============================================================================

chcp 65001 > nul

echo 🚀 KRAI Engine Docker Setup
echo ============================
echo.
echo NOTE: For Windows 10/11, consider using setup.ps1 (PowerShell) instead.
echo       setup.ps1 is more modern and maintainable than this batch script.
echo       To use PowerShell: .\setup.ps1
echo.

where powershell >nul 2>&1
if errorlevel 1 (
    echo ❌ Error: PowerShell is required but not available on this system.
    exit /b 1
)

for /f "delims=" %%i in ('powershell -NoProfile -Command "$PSVersionTable.PSVersion.Major"') do set "PS_VERSION_MAJOR=%%i"
if not defined PS_VERSION_MAJOR (
    echo ❌ Error: Unable to determine PowerShell version.
    exit /b 1
)
for /f "delims=" %%i in ('powershell -NoProfile -Command "$PSVersionTable.PSEdition"') do set "PS_EDITION=%%i"
if not defined PS_EDITION set "PS_EDITION=Desktop"
if %PS_VERSION_MAJOR% LSS 5 (
    echo ❌ Error: PowerShell 5.0 or higher is required for RSA key generation (ExportPkcs8PrivateKey).
    echo    Please upgrade PowerShell and rerun this script.
    exit /b 1
)

set "RSA_GENERATION_METHOD=POWERSHELL"
for /f "delims=" %%i in ('powershell -NoProfile -Command "$ErrorActionPreference='SilentlyContinue'; $rsa=[System.Security.Cryptography.RSA]::Create(2048); try { $null = $rsa.ExportPkcs8PrivateKey(); 'SUPPORTED' } catch { 'MISSING' } finally { $rsa.Dispose() }"') do set "RSA_EXPORT_STATUS=%%i"
if /I "!RSA_EXPORT_STATUS!"=="SUPPORTED" (
    set "RSA_GENERATION_METHOD=POWERSHELL"
) else (
    where openssl >nul 2>&1
    if errorlevel 1 (
        echo ❌ Error: PowerShell !PS_VERSION_MAJOR!.x (!PS_EDITION!) lacks ExportPkcs8PrivateKey and openssl.exe is not available on PATH.
        echo    Install PowerShell 7+ (Core edition) or add OpenSSL to PATH, then rerun this script.
        exit /b 1
    )
    set "RSA_GENERATION_METHOD=OPENSSL"
)

call :PrepareEnvOutput
set "PREPARE_STATUS=%errorlevel%"
if "%PREPARE_STATUS%"=="2" exit /b 0
if "%PREPARE_STATUS%"=="1" exit /b 1

set "PWGEN_CMD=powershell -NoProfile -Command "$bytes = New-Object byte[] 48; (New-Object Security.Cryptography.RNGCryptoServiceProvider).GetBytes($bytes); $text = [Convert]::ToBase64String($bytes) -replace '[+/=]',''; $text.Substring(0,32)""

echo 🔐 Generating secure passwords and keys...
echo    This may take a moment for RSA key generation...
echo.

REM Database credentials
for /f "delims=" %%i in ('!PWGEN_CMD!') do set "DB_PASSWORD=%%i"

REM Object Storage credentials
for /f "delims=" %%i in ('!PWGEN_CMD!') do set "MINIO_SECRET_KEY=%%i"

REM Authentication & Security
echo    Generating RSA keypair for JWT...
call :GenerateRSAKeys
if errorlevel 1 exit /b 1

for /f "delims=" %%i in ('!PWGEN_CMD!') do set "ADMIN_PASSWORD=%%i"

REM Docker Compose services
for /f "delims=" %%i in ('!PWGEN_CMD!') do set "N8N_PASSWORD=%%i"
for /f "delims=" %%i in ('!PWGEN_CMD!') do set "N8N_DB_PASSWORD=%%i"
for /f "delims=" %%i in ('!PWGEN_CMD!') do set "PGADMIN_PASSWORD=%%i"
for /f "delims=" %%i in ('!PWGEN_CMD!') do set "FIRECRAWL_BULL_KEY=%%i"

REM Test environment
for /f "delims=" %%i in ('!PWGEN_CMD!') do set "TEST_DB_PASSWORD=%%i"
for /f "delims=" %%i in ('powershell -NoProfile -Command "[System.Uri]::EscapeDataString($env:TEST_DB_PASSWORD)"') do set "TEST_DB_PASSWORD_URL=%%i"
for /f "delims=" %%i in ('!PWGEN_CMD!') do set "TEST_STORAGE_KEY=%%i"
for /f "delims=" %%i in ('!PWGEN_CMD!') do set "TEST_FIRECRAWL_KEY=%%i"

echo Creating .env file with generated credentials...

del .env 2>nul

> .env echo # ==========================================
>> .env echo # KRAI ENGINE ENVIRONMENT CONFIGURATION
>> .env echo # ==========================================
>> .env echo # Auto-generated by setup.bat on %date% %time%
>> .env echo # NEVER commit this populated .env file to version control!
>> .env echo # Review and customize these values before production deployment.
>> .env echo # ----------------------------------------------------------------------------
>> .env echo # Copy this file to `.env` and adjust values before running the stack.
>> .env echo # Use `./setup.sh` (Linux/macOS) or `setup.bat` (Windows) to generate secrets automatically.
>> .env echo # Keep this file version-controlled for reference, but never commit a populated `.env` file.
>> .env echo # Store production credentials in a secure secrets manager (1Password, Vault, etc.).
>> .env echo # ----------------------------------------------------------------------------
>> .env echo # Environment loading guidance:
>> .env echo # - Prefer maintaining a single `.env` at the repository root.
>> .env echo # - Legacy scripts that call `load_dotenv(".env.database")` should be updated to call `load_dotenv()` without arguments.
>> .env echo # - Until updated, you may create a local `.env.database` that mirrors the variables defined in your root `.env`.
>> .env echo # - Prefer using `scripts/_env.load_env()` in Python helpers and passing `extra_files=['.env.database']` only when a legacy override is required.
>> .env echo # ----------------------------------------------------------------------------
>> .env echo # Pro Tip: Comment out sections you do not use to avoid accidentally mixing configs.
>> .env echo.
>> .env echo # ==========================================
>> .env echo # APPLICATION SETTINGS
>> .env echo # ==========================================
>> .env echo # Runtime environment: production, staging, development
>> .env echo ENV=production
>> .env echo.
>> .env echo # Backend API host binding (0.0.0.0 for Docker, 127.0.0.1 for local only)
>> .env echo API_HOST=0.0.0.0
>> .env echo.
>> .env echo # Backend API port (FastAPI / Uvicorn)
>> .env echo API_PORT=8000
>> .env echo.
>> .env echo # Global log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
>> .env echo LOG_LEVEL=DEBUG
>> .env echo.
>> .env echo.
>> .env echo # ==========================================
>> .env echo # DATABASE CONFIGURATION
>> .env echo # ==========================================
>> .env echo # Choose PostgreSQL OR Supabase, not both at the same time.
>> .env echo.
>> .env echo # --- PostgreSQL (Docker/Local) ---
>> .env echo # Database backend type: postgresql or sqlite (PostgreSQL recommended)
>> .env echo DATABASE_TYPE=postgresql
>> .env echo.
>> .env echo # Hostname for local Docker Compose service
>> .env echo DATABASE_HOST=krai-postgres
>> .env echo.
>> .env echo # PostgreSQL service port
>> .env echo DATABASE_PORT=5432
>> .env echo.
>> .env echo # Database name for local deployment
>> .env echo DATABASE_NAME=krai
>> .env echo.
>> .env echo # PostgreSQL username used by the application
>> .env echo DATABASE_USER=krai_user
>> .env echo.
>> .env echo # PostgreSQL password (change for production!)
>> .env echo DATABASE_PASSWORD=!DB_PASSWORD!
>> .env echo.
>> .env echo # --- Supabase (Cloud) ---
>> .env echo # Supabase project URL (https://<project>.supabase.co)
>> .env echo SUPABASE_URL=https://your-project.supabase.co
>> .env echo.
>> .env echo # Supabase anonymous key (client-side usage)
>> .env echo SUPABASE_ANON_KEY=your-anon-key-here
>> .env echo.
>> .env echo # Supabase service role key (server-side only, keep secret!)
>> .env echo SUPABASE_SERVICE_ROLE_KEY=your-service-role-key-here
>> .env echo.
>> .env echo # Supabase storage API base URL
>> .env echo SUPABASE_STORAGE_URL=https://your-project.supabase.co/storage/v1
>> .env echo.
>> .env echo # Optional password for direct Supabase PostgreSQL connections (deprecated scripts only)
>> .env echo #SUPABASE_DB_PASSWORD=your-supabase-db-password
>> .env echo.
>> .env echo # Direct PostgreSQL connection string (optional alternative to local DB)
>> .env echo DATABASE_CONNECTION_URL=postgresql://postgres:your-password@db.your-project.supabase.co:5432/postgres
>> .env echo.
>> .env echo # Optional (deprecated) legacy alias used by older scripts — prefer DATABASE_CONNECTION_URL
>> .env echo #DATABASE_URL=postgresql://krai_user:krai_secure_password@krai-postgres:5432/krai            # Local PostgreSQL example
>> .env echo #DATABASE_URL=postgresql://postgres:your-password@db.your-project.supabase.co:5432/postgres  # Supabase example
>> .env echo.
>> .env echo.
>> .env echo # ==========================================
>> .env echo # OBJECT STORAGE CONFIGURATION
>> .env echo # ==========================================
>> .env echo # MinIO S3-compatible storage for your deployment target.
>> .env echo.
>> .env echo # --- MinIO (Docker/Local) ---
>> .env echo # Object storage implementation (S3-compatible (MinIO))
>> .env echo OBJECT_STORAGE_TYPE=s3
>> .env echo.
>> .env echo # Internal endpoint for MinIO service in Docker
>> .env echo OBJECT_STORAGE_ENDPOINT=http://krai-minio:9000
>> .env echo.
>> .env echo # Optional (deprecated) legacy alias mirroring OBJECT_STORAGE_ENDPOINT
>> .env echo #MINIO_ENDPOINT=http://krai-minio:9000
>> .env echo.
>> .env echo # MinIO access key (change for production!)
>> .env echo OBJECT_STORAGE_ACCESS_KEY=minioadmin
>> .env echo.
>> .env echo # MinIO secret key (change for production!)
>> .env echo OBJECT_STORAGE_SECRET_KEY=!MINIO_SECRET_KEY!
>> .env echo.
>> .env echo # AWS region style identifier (MinIO accepts any string)
>> .env echo OBJECT_STORAGE_REGION=us-east-1
>> .env echo.
>> .env echo # Set to true if MinIO endpoint uses HTTPS (self-hosted defaults to false)
>> .env echo OBJECT_STORAGE_USE_SSL=false
>> .env echo.
>> .env echo # Public URL used by the frontend to access stored files
>> .env echo OBJECT_STORAGE_PUBLIC_URL=http://localhost:9000
>> .env echo.
>> .env echo # Per-bucket public URLs used by image download/delete bucket inference
>> .env echo OBJECT_STORAGE_PUBLIC_URL_DOCUMENTS=http://localhost:9000/documents
>> .env echo OBJECT_STORAGE_PUBLIC_URL_ERROR=http://localhost:9000/error-images
>> .env echo OBJECT_STORAGE_PUBLIC_URL_PARTS=http://localhost:9000/parts-images
>> .env echo.
>> .env echo.
>> .env echo.
>> .env echo # ==========================================
>> .env echo # AI SERVICE CONFIGURATION
>> .env echo # ==========================================
>> .env echo # Consolidated configuration for Ollama-based AI services and GPU controls.
>> .env echo.
>> .env echo # --- Ollama Base ---
>> .env echo # AI service provider type (ollama or openai). Currently supports `ollama`.
>> .env echo AI_SERVICE_TYPE=ollama
>> .env echo.
>> .env echo # Base URL for internal AI service abstraction (used by backend)
>> .env echo AI_SERVICE_URL=http://krai-ollama:11434
>> .env echo.
>> .env echo # Ollama server URL (used by backend - consistent naming)
>> .env echo # Note: Backend uses OLLAMA_URL, not OLLAMA_BASE_URL or AI_SERVICE_URL
>> .env echo OLLAMA_URL=http://krai-ollama:11434
>> .env echo # For host CLI/testing, you may override with http://localhost:11434
>> .env echo.
>> .env echo # --- Ollama Models ---
>> .env echo # Embedding model (vector generation for semantic search)
>> .env echo OLLAMA_MODEL_EMBEDDING=nomic-embed-text:latest
>> .env echo.
>> .env echo # Structured extraction model (product specs as JSON)
>> .env echo OLLAMA_MODEL_EXTRACTION=qwen2.5:3b
>> .env echo.
>> .env echo # Conversational model (agent/chat responses)
>> .env echo OLLAMA_MODEL_CHAT=llama3.2:3b
>> .env echo.
>> .env echo # Vision-capable model (diagram/OCR understanding)
>> .env echo OLLAMA_MODEL_VISION=llava:7b
>> .env echo.
>> .env echo # Legacy/fallback text model (deprecated path support)
>> .env echo OLLAMA_MODEL_TEXT=qwen2.5:3b
>> .env echo.
>> .env echo # Context window tokens for Ollama prompts (higher requires more VRAM)
>> .env echo OLLAMA_NUM_CTX=8192
>> .env echo.
>> .env echo # --- Vision Processing ---
>> .env echo # Disable AI-based vision analysis entirely (images still extracted locally)
>> .env echo DISABLE_VISION_PROCESSING=false
>> .env echo.
>> .env echo # Maximum number of images analyzed per document (tune for VRAM limits)
>> .env echo MAX_VISION_IMAGES=5
>> .env echo.
>> .env echo # --- Solution Translation ---
>> .env echo # Enable automatic translation of troubleshooting steps via LLM
>> .env echo ENABLE_SOLUTION_TRANSLATION=false
>> .env echo.
>> .env echo # Target language for solution translation (ISO code, e.g. de, en, fr)
>> .env echo SOLUTION_TRANSLATION_LANGUAGE=de
>> .env echo.
>> .env echo # --- LLM Extraction Controls ---
>> .env echo # Maximum document pages scanned by LLM extraction (0 = all pages, -1 = disabled)
>> .env echo LLM_MAX_PAGES=50
>> .env echo.
>> .env echo # --- GPU Configuration ---
>> .env echo # Enable GPU acceleration for OpenCV/ML pipelines (requires CUDA drivers)
>> .env echo USE_GPU=false
>> .env echo.
>> .env echo # CUDA device index to target (0 = primary GPU)
>> .env echo CUDA_VISIBLE_DEVICES=0
>> .env echo.
>> .env echo # --- Visual Embeddings ---
>> .env echo # Vision embedding model identifier (used for multimodal search indexing)
>> .env echo AI_VISUAL_EMBEDDING_MODEL=vidore/colqwen2.5-v0.2
>> .env echo.
>> .env echo.
>> .env echo # ==========================================
>> .env echo # AUTHENTICATION & SECURITY
>> .env echo # ==========================================
>> .env echo # Generate fresh RSA keys for production and keep them secret!
>> .env echo.
>> .env echo # --- JWT Configuration ---
>> .env echo # JWT signing algorithm (RS256 recommended for asymmetric keys)
>> .env echo JWT_ALGORITHM=RS256
>> .env echo.
>> .env echo # Access token lifetime in minutes
>> .env echo JWT_ACCESS_TOKEN_EXPIRE_MINUTES=60
>> .env echo.
>> .env echo # Refresh token lifetime in days
>> .env echo JWT_REFRESH_TOKEN_EXPIRE_DAYS=30
>> .env echo.
>> .env echo # Base64-encoded PKCS8 private key (see instructions below)
>> .env echo JWT_PRIVATE_KEY=!JWT_PRIVATE_KEY!
>> .env echo.
>> .env echo # Base64-encoded SubjectPublicKeyInfo public key
>> .env echo JWT_PUBLIC_KEY=!JWT_PUBLIC_KEY!
>> .env echo.
>> .env echo # PowerShell key generation:
>> .env echo #   $key = New-Object System.Security.Cryptography.RSACryptoServiceProvider 2048
>> .env echo #   [Convert]::ToBase64String($key.ExportPkcs8PrivateKey())
>> .env echo #   [Convert]::ToBase64String($key.ExportSubjectPublicKeyInfo())
>> .env echo # OpenSSL alternative:
>> .env echo #   openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out jwt_private.pem
>> .env echo #   openssl rsa -in jwt_private.pem -pubout -out jwt_public.pem
>> .env echo #   base64 -w0 jwt_private.pem
>> .env echo #   base64 -w0 jwt_public.pem
>> .env echo.
>> .env echo # --- Security Controls ---
>> .env echo # Maximum failed login attempts before account lockout
>> .env echo MAX_LOGIN_ATTEMPTS=5
>> .env echo.
>> .env echo # Account lockout duration in minutes
>> .env echo ACCOUNT_LOCKOUT_DURATION_MINUTES=15
>> .env echo.
>> .env echo # Password complexity requirements
>> .env echo PASSWORD_REQUIRE_UPPERCASE=true
>> .env echo PASSWORD_REQUIRE_LOWERCASE=true
>> .env echo PASSWORD_REQUIRE_NUMBER=true
>> .env echo PASSWORD_REQUIRE_SPECIAL=true
>> .env echo.
>> .env echo # Minimum password length enforced by backend validation
>> .env echo PASSWORD_MIN_LENGTH=12
>> .env echo.
>> .env echo # --- Session Management ---
>> .env echo # Session idle timeout in minutes
>> .env echo SESSION_TIMEOUT_MINUTES=60
>> .env echo.
>> .env echo # Remember-me token lifetime in days
>> .env echo REMEMBER_ME_DAYS=30
>> .env echo.
>> .env echo # --- Default Admin Bootstrap ---
>> .env echo # Default admin email created on first startup ^(override before production!^)
>> .env echo DEFAULT_ADMIN_EMAIL=admin@example.com
>> .env echo.
>> .env echo # Default admin username
>> .env echo DEFAULT_ADMIN_USERNAME=admin
>> .env echo.
>> .env echo # Default admin first name
>> .env echo DEFAULT_ADMIN_FIRST_NAME=System
>> .env echo.
>> .env echo # Default admin last name
>> .env echo DEFAULT_ADMIN_LAST_NAME=Administrator
>> .env echo.
>> .env echo # Default admin password ^(leave blank to prompt during setup^)
>> .env echo DEFAULT_ADMIN_PASSWORD=!ADMIN_PASSWORD!
>> .env echo.
>> .env echo.
>> .env echo # ==========================================
>> .env echo # PROCESSING PIPELINE SETTINGS
>> .env echo # ==========================================
>> .env echo # Toggle specific extraction steps for debugging or resource management.
>> .env echo.
>> .env echo # Extract product models from manuals ^(recommended: true^)
>> .env echo ENABLE_PRODUCT_EXTRACTION=true
>> .env echo.
>> .env echo # Extract spare parts catalogs ^(recommended for service manuals^)
>> .env echo ENABLE_PARTS_EXTRACTION=true
>> .env echo.
>> .env echo # Extract diagnostic error codes ^(recommended: true^)
>> .env echo ENABLE_ERROR_CODE_EXTRACTION=true
>> .env echo.
>> .env echo # Extract document version metadata ^(recommended: true^)
>> .env echo ENABLE_VERSION_EXTRACTION=true
>> .env echo.
>> .env echo # Extract inline images from PDFs ^(recommended: true^)
>> .env echo ENABLE_IMAGE_EXTRACTION=true
>> .env echo.
>> .env echo # Run OCR on extracted images for searchable text ^(depends on Tesseract/OpenCV^)
>> .env echo ENABLE_OCR=true
>> .env echo.
>> .env echo # Run AI-based vision analysis on extracted images ^(set false if low VRAM^)
>> .env echo ENABLE_VISION_AI=true
>> .env echo.
>> .env echo # Extract outbound links and embedded videos for enrichment
>> .env echo ENABLE_LINK_EXTRACTION=true
>> .env echo.
>> .env echo # Generate embeddings for semantic search ^(required for vector search^)
>> .env echo ENABLE_EMBEDDINGS=true
>> .env echo.
>> .env echo.
>> .env echo # ==========================================
>> .env echo # WEB SCRAPING CONFIGURATION
>> .env echo # ==========================================
>> .env echo # Controls the scraping backend ^(BeautifulSoup, Firecrawl^) and related services.
>> .env echo.
>> .env echo # --- Scraping Backend Selection ---
>> .env echo # Available options: beautifulsoup ^(local HTML parsing^), firecrawl ^(cloud service^)
>> .env echo SCRAPING_BACKEND=beautifulsoup
>> .env echo.
>> .env echo # Enable post-processing link enrichment to fetch additional metadata
>> .env echo ENABLE_LINK_ENRICHMENT=true
>> .env echo.
>> .env echo # Enable manufacturer crawling workflows ^(Firecrawl recommended^)
>> .env echo ENABLE_MANUFACTURER_CRAWLING=false
>> .env echo.
>> .env echo # --- Firecrawl Configuration ^(Only if SCRAPING_BACKEND=firecrawl^) ---
>> .env echo # Firecrawl API base URL ^(self-hosted or cloud endpoint^)
>> .env echo FIRECRAWL_API_URL=http://localhost:3002
>> .env echo.
>> .env echo # LLM provider name used by Firecrawl ^(openai, ollama, etc.^)
>> .env echo FIRECRAWL_LLM_PROVIDER=ollama
>> .env echo.
>> .env echo # Default LLM model for summarization/extraction via Firecrawl
>> .env echo FIRECRAWL_MODEL_NAME=qwen2.5:3b
>> .env echo.
>> .env echo # Embedding model for Firecrawl vector outputs
>> .env echo FIRECRAWL_EMBEDDING_MODEL=nomic-embed-text:latest
>> .env echo.
>> .env echo # Maximum concurrent Firecrawl jobs allowed
>> .env echo FIRECRAWL_MAX_CONCURRENCY=3
>> .env echo.
>> .env echo # Block heavy media downloads during scraping ^(true/false^)
>> .env echo FIRECRAWL_BLOCK_MEDIA=true
>> .env echo.
>> .env echo # Allow callbacks to local webhook endpoints ^(set false for production^)
>> .env echo FIRECRAWL_ALLOW_LOCAL_WEBHOOKS=true
>> .env echo.
>> .env echo # Optional proxy configuration ^(leave blank if unused^)
>> .env echo FIRECRAWL_PROXY_SERVER=
>> .env echo FIRECRAWL_PROXY_USERNAME=
>> .env echo FIRECRAWL_PROXY_PASSWORD=
>> .env echo.
>> .env echo # Maximum scrape duration per request in seconds
>> .env echo FIRECRAWL_SCRAPE_TIMEOUT=120
>> .env echo.
>> .env echo # Maximum crawl duration for multi-page jobs in seconds
>> .env echo FIRECRAWL_CRAWL_TIMEOUT=600
>> .env echo.
>> .env echo # Retry attempts for failed Firecrawl jobs
>> .env echo FIRECRAWL_RETRIES=2
>> .env echo.
>> .env echo # Optional OpenAI API key ^(required if FIRECRAWL_LLM_PROVIDER=openai^)
>> .env echo OPENAI_API_KEY=
>> .env echo.
>> .env echo.
>> .env echo # ==========================================
>> .env echo # EXTERNAL API KEYS ^& TUNNELS
>> .env echo # ==========================================
>> .env echo # Keep all third-party credentials secret. Rotate keys regularly.
>> .env echo.
>> .env echo # --- YouTube Data API ---
>> .env echo # Obtain from https://console.cloud.google.com/apis/credentials ^(10k daily quota^)
>> .env echo YOUTUBE_API_KEY=
>> .env echo.
>> .env echo # --- Cloudflare Tunnels ^(Optional^) ---
>> .env echo # Tunnel token for exposing n8n or automation webhook endpoints
>> .env echo CLOUDFLARE_TUNNEL_TOKEN=
>> .env echo.
>> .env echo # Public hostname for n8n automation platform
>> .env echo N8N_HOST=workflow.your-domain.com
>> .env echo.
>> .env echo # Public webhook URL for n8n workflows
>> .env echo WEBHOOK_URL=https://workflow.your-domain.com/
>> .env echo.
>> .env echo # Tunnel token for exposing Ollama securely over the internet
>> .env echo CLOUDFLARE_TUNNEL_TOKEN_OLLAMA=your-ollama-tunnel-token-here
>> .env echo.
>> .env echo # Public hostname for remote Ollama access ^(Cloudflare Tunnel^)
>> .env echo # This is different from OLLAMA_URL ^(internal Docker network^)
>> .env echo OLLAMA_BASE_URL=https://llm.your-domain.com
>> .env echo.
>> .env echo.
>> .env echo # ==========================================
>> .env echo # DOCKER COMPOSE CONFIGURATION
>> .env echo # ==========================================
>> .env echo # Variables specific to Docker Compose deployments
>> .env echo.
>> .env echo # --- n8n Configuration ---
>> .env echo # n8n basic auth username
>> .env echo N8N_BASIC_AUTH_USER=admin
>> .env echo.
>> .env echo # n8n basic auth password ^(change for production!^)
>> .env echo N8N_BASIC_AUTH_PASSWORD=!N8N_PASSWORD!
>> .env echo.
>> .env echo # n8n separate database password ^(different from main KRAI DB^)
>> .env echo N8N_DATABASE_PASSWORD=!N8N_DB_PASSWORD!
>> .env echo.
>> .env echo # --- pgAdmin Configuration ---
>> .env echo # pgAdmin default admin email
>> .env echo PGADMIN_DEFAULT_EMAIL=admin@krai.local
>> .env echo.
>> .env echo # pgAdmin default admin password ^(change for production!^)
>> .env echo PGADMIN_DEFAULT_PASSWORD=!PGADMIN_PASSWORD!
>> .env echo.
>> .env echo # --- MinIO Browser Configuration ---
>> .env echo # MinIO browser redirect URL ^(for console access^)
>> .env echo MINIO_BROWSER_REDIRECT_URL=http://localhost:9001
>> .env echo.
>> .env echo # --- Firecrawl Bull Queue ---
>> .env echo # Firecrawl Bull queue authentication key ^(change for production!^)
>> .env echo FIRECRAWL_BULL_AUTH_KEY=!FIRECRAWL_BULL_KEY!
>> .env echo.
>> .env echo # --- Playwright Configuration ---
>> .env echo # Playwright workspace auto-cleanup ^(true/false^)
>> .env echo PLAYWRIGHT_WORKSPACE_DELETE_EXPIRED=true
>> .env echo.
>> .env echo # Playwright workspace expiry in days
>> .env echo PLAYWRIGHT_WORKSPACE_EXPIRY_DAYS=1
>> .env echo.
>> .env echo # --- Grafana Configuration ^(Enterprise^) ---
>> .env echo # Grafana allow user sign-up ^(true/false^)
>> .env echo GRAFANA_ALLOW_SIGN_UP=false
>> .env echo.
>> .env echo # --- Redis Configuration ---
>> .env echo # Redis URL for application cache ^(optional^)
>> .env echo REDIS_URL=redis://krai-redis:6379
>> .env echo.
>> .env echo # --- Test Environment Variables ---
>> .env echo # Test database name ^(separate from production^)
>> .env echo TEST_DATABASE_NAME=krai_test
>> .env echo.
>> .env echo # Test database user
>> .env echo TEST_DATABASE_USER=krai_test
>> .env echo.
>> .env echo # Test database password
>> .env echo TEST_DATABASE_PASSWORD=!TEST_DB_PASSWORD!
>> .env echo.
>> .env echo # Test database connection URL
>> .env echo TEST_DATABASE_URL=postgresql://krai_test:!TEST_DB_PASSWORD_URL!@postgresql-test:5432/krai_test
>> .env echo.
>> .env echo # Test storage access key
>> .env echo TEST_STORAGE_ACCESS_KEY=test_access_key
>> .env echo.
>> .env echo # Test storage secret key
>> .env echo TEST_STORAGE_SECRET_KEY=!TEST_STORAGE_KEY!
>> .env echo.
>> .env echo # Test storage endpoint
>> .env echo TEST_STORAGE_ENDPOINT=minio-test:9000
>> .env echo.
>> .env echo # Test Firecrawl Bull auth key
>> .env echo TEST_FIRECRAWL_BULL_AUTH_KEY=!TEST_FIRECRAWL_KEY!
>> .env echo.
>> .env echo.
>> .env echo # ==========================================
>> .env echo # SECURITY REMINDERS ^& DOCUMENTATION
>> .env echo # ==========================================
>> .env echo # - NEVER commit your populated `.env` file to version control.
>> .env echo # - Rotate secrets immediately if they leak or when personnel changes.
>> .env echo # - Store production secrets in a secure, access-controlled vault.
>> .env echo # - Review `docs/DOCKER_SETUP.md` for full deployment instructions.
>> .env echo # - Use `./setup.sh` or `setup.bat` to bootstrap local development safely.

echo ✅ .env file created successfully!
echo.
echo ═══════════════════════════════════════════════════════════════
echo 🔑 GENERATED CREDENTIALS ^(Keep these secure!^)
echo ═══════════════════════════════════════════════════════════════
echo.
echo 📊 DATABASE:
echo    PostgreSQL Password:     !DB_PASSWORD!
echo    n8n Database Password:   !N8N_DB_PASSWORD!
echo    Test Database Password:  !TEST_DB_PASSWORD!
echo.
echo 💾 OBJECT STORAGE:
echo    MinIO Secret Key:        !MINIO_SECRET_KEY!
echo    Test Storage Key:        !TEST_STORAGE_KEY!
echo.
echo 🔐 AUTHENTICATION:
echo    Admin Password:          !ADMIN_PASSWORD!
echo    JWT Private Key:         ^[Generated - see .env^]
echo    JWT Public Key:          ^[Generated - see .env^]
echo.
echo 🐳 DOCKER SERVICES:
echo    n8n Password:            !N8N_PASSWORD!
echo    pgAdmin Password:        !PGADMIN_PASSWORD!
echo    Firecrawl Bull Key:      !FIRECRAWL_BULL_KEY!
echo    Test Firecrawl Key:      !TEST_FIRECRAWL_KEY!
echo.
echo ═══════════════════════════════════════════════════════════════
echo.
echo ⚠️  IMPORTANT SECURITY NOTES:
echo    • NEVER commit .env to version control ^(already in .gitignore^)
echo    • Store these credentials in a secure password manager
echo    • For production: Review and customize all values in .env
echo    • Rotate secrets regularly ^(every 90 days recommended^)
echo.
echo 📝 MANUAL CONFIGURATION REQUIRED:
echo    • YOUTUBE_API_KEY: Get from https://console.cloud.google.com/apis/credentials
echo    • CLOUDFLARE_TUNNEL_TOKEN: Get from https://dash.cloudflare.com/
echo    • Review all AI model names in AI SERVICE CONFIGURATION section
echo.
echo ═══════════════════════════════════════════════════════════════
echo.
echo 📋 NEXT STEPS:
echo    1. Review .env file and customize as needed
echo    2. Start Docker: docker-compose -f docker-compose.simple.yml up -d
echo    3. Check status:  docker-compose -f docker-compose.simple.yml ps
echo    4. View logs:     docker-compose -f docker-compose.simple.yml logs -f
echo    5. Access API:    curl http://localhost:8000/health
echo    6. Access UI:     http://localhost:3000
echo.
echo 📚 DOCUMENTATION:
echo    • Full setup guide: DOCKER_SETUP.md
echo    • Deployment guide: DEPLOYMENT.md
echo    • Database schema: DATABASE_SCHEMA.md
echo.
echo 🔍 Validating generated .env file...

if not exist .env (
    echo ❌ Error: .env file was not created!
    pause
    exit /b 1
)

for %%A in (.env) do set "ENV_SIZE=%%~zA"
if %ENV_SIZE% LSS 1000 (
    echo ❌ Warning: .env file seems incomplete ^(size: %ENV_SIZE% bytes^)
    echo    Expected size: ~15000+ bytes
    pause
)

echo ✅ Validation passed!
echo.
echo 🎉 Setup complete! Your KRAI Engine is ready to start.
pause
endlocal
exit /b 0

:GenerateRSAKeys
set "JWT_PRIVATE_KEY="
set "JWT_PUBLIC_KEY="
if /I "%RSA_GENERATION_METHOD%"=="POWERSHELL" (
    for /f "tokens=1,* delims=:" %%a in ('powershell -NoProfile -Command "$ErrorActionPreference='Stop'; $rsa = [System.Security.Cryptography.RSA]::Create(2048); try { 'PRIVATE:' + [Convert]::ToBase64String($rsa.ExportPkcs8PrivateKey()); 'PUBLIC:' + [Convert]::ToBase64String($rsa.ExportSubjectPublicKeyInfo()); } finally { $rsa.Dispose() }"') do (
        if "%%a"=="PRIVATE" set "JWT_PRIVATE_KEY=%%b"
        if "%%a"=="PUBLIC" set "JWT_PUBLIC_KEY=%%b"
    )
) else (
    set "RSA_PRIVATE_TEMP=%TEMP%\krai_rsa_private_%RANDOM%.pem"
    set "RSA_PRIVATE_DER=%TEMP%\krai_rsa_private_%RANDOM%.der"
    set "RSA_PUBLIC_DER=%TEMP%\krai_rsa_public_%RANDOM%.der"
    openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "%RSA_PRIVATE_TEMP%" >nul 2>&1
    if errorlevel 1 (
        echo ❌ Error: OpenSSL failed to generate RSA private key.
        del "%RSA_PRIVATE_TEMP%" "%RSA_PRIVATE_DER%" "%RSA_PUBLIC_DER%" 2>nul
        exit /b 1
    )
    openssl pkcs8 -topk8 -inform PEM -outform DER -nocrypt -in "%RSA_PRIVATE_TEMP%" -out "%RSA_PRIVATE_DER%" >nul 2>&1
    if errorlevel 1 (
        echo ❌ Error: OpenSSL failed to export RSA private key in PKCS8 format.
        del "%RSA_PRIVATE_TEMP%" "%RSA_PRIVATE_DER%" "%RSA_PUBLIC_DER%" 2>nul
        exit /b 1
    )
    openssl rsa -in "%RSA_PRIVATE_TEMP%" -pubout -outform DER -out "%RSA_PUBLIC_DER%" >nul 2>&1
    if errorlevel 1 (
        echo ❌ Error: OpenSSL failed to export RSA public key.
        del "%RSA_PRIVATE_TEMP%" "%RSA_PRIVATE_DER%" "%RSA_PUBLIC_DER%" 2>nul
        exit /b 1
    )
    for /f "delims=" %%i in ('powershell -NoProfile -Command "[Convert]::ToBase64String([IO.File]::ReadAllBytes('%RSA_PRIVATE_DER%'))"') do set "JWT_PRIVATE_KEY=%%i"
    for /f "delims=" %%i in ('powershell -NoProfile -Command "[Convert]::ToBase64String([IO.File]::ReadAllBytes('%RSA_PUBLIC_DER%'))"') do set "JWT_PUBLIC_KEY=%%i"
    del "%RSA_PRIVATE_TEMP%" "%RSA_PRIVATE_DER%" "%RSA_PUBLIC_DER%" 2>nul
)

if not defined JWT_PRIVATE_KEY (
    echo ❌ Error: Failed to generate JWT private key.
    exit /b 1
)

if not defined JWT_PUBLIC_KEY (
    echo ❌ Error: Failed to generate JWT public key.
    exit /b 1
)

exit /b 0

:BackupEnvFile
for /f "delims=" %%i in ('powershell -NoProfile -Command "Get-Date -Format \"yyyyMMdd_HHmmss\""') do set "TIMESTAMP=%%i"
if not defined TIMESTAMP (
    set "TIMESTAMP=%DATE:~10,4%%DATE:~4,2%%DATE:~7,2%_%TIME:~0,2%%TIME:~3,2%%TIME:~6,2%"
    set "TIMESTAMP=%TIMESTAMP: =0%"
)
set "BACKUP_PATH=.env.bak.%TIMESTAMP%"
copy /Y .env "%BACKUP_PATH%" >nul
if errorlevel 1 (
    echo ❌ Error: Failed to create backup at %BACKUP_PATH%.
    exit /b 1
)
echo 📦 Existing .env backed up to %BACKUP_PATH%.
exit /b 0

:PrepareEnvOutput
if not exist .env (
    exit /b 0
)

if "%FORCE_OVERWRITE%"=="1" (
    call :BackupEnvFile
    if errorlevel 1 exit /b 1
    exit /b 0
)

choice /M "Overwrite existing .env and create backup?"
if errorlevel 255 (
    echo ❌ Error: .env already exists and no interactive console is available to confirm overwrite.
    echo    Re-run with --force or set FORCE=1 to overwrite automatically.
    exit /b 1
)
if errorlevel 2 (
    echo ℹ️  Aborting without modifying .env.
    exit /b 2
)

call :BackupEnvFile
if errorlevel 1 exit /b 1
exit /b 0
