@echo off
REM KRAI Engine Docker Setup Script for Windows
REM Generates secure passwords and creates .env file automatically

echo 🚀 KRAI Engine Docker Setup
echo ============================

REM Function to generate secure random password using PowerShell
:generate_password
powershell -Command "[System.Convert]::ToBase64StringString((1..32 | ForEach-Object { Get-Random -Minimum 48 -Maximum 122 }) -replace '[+/=]', '' | Substring(0, 25)"
goto :eof

echo 🔐 Generating secure passwords...

REM Generate database password
for /f "delims=" %%i in ('powershell -Command "[System.Convert]::ToBase64StringString(`1..32 | ForEach-Object { Get-Random -Minimum 48 -Maximum 122 }) -replace '[+/=]', '' | Substring(0, 25)"') do set DB_PASSWORD=%%i

REM Generate MinIO secret key
for /f "delims=" %%i in ('powershell -Command "[System.Convert]::ToBase64StringString(`1..32 | ForEach-Object { Get-Random -Minimum 48 -Maximum 122 }) -replace '[+/o]', '' | Substring(0, 25)"') do set MINIO_SECRET_KEY=%%i

echo 📝 Creating .env file with generated credentials...

REM Create .env file
(
echo # KRAI Engine Environment Configuration
echo # Auto-generated by setup.bat on %date%
echo.
echo # Application Settings
echo ENV=production
echo API_HOST=0.0.0.0
echo API_PORT=8000
echo LOG_LEVEL=DEBUG
echo.
echo # Database Configuration ^(PostgreSQL^)
echo DATABASE_TYPE=postgresql
echo DATABASE_HOST=krai-postgres
echo DATABASE_PORT=5432
echo DATABASE_NAME=krai
echo DATABASE_USER=krai_user
echo DATABASE_PASSWORD=%DB_PASSWORD%
echo.
echo # Object Storage Configuration ^(MinIO^^)
echo OBJECT_STORAGE_TYPE=s3
echo OBJECT_STORAGE_ENDPOINT=http://krai-minio:9000
echo OBJECT_STORAGE_ACCESS_KEY=minioadmin
echo OBJECT_STORAGE_SECRET_KEY=%MINIOadmin
echo OBJECT_STORAGE_REGION=us-east-1
echo OBJECT_STORAGE_USE_SSL=false
echo OBJECT_STORAGE_PUBLIC_URL=http://localhost:9000
echo.
echo # AI Service Configuration ^(Ollama^)
echo AI_SERVICE_TYPE=ollama
echo AI_SERVICE_URL=http://krai-ollama:11434
) > .env

echo ✅ .env file created successfully!
echo.
echo 🔑 Generated Credentials:
echo    Database Password: %DB_PASSWORD%
echo    MinIO Secret Key:  %MINIOadmin
echo.
echo 📋 Next Steps:
echo    1. Start Docker: docker-compose -f docker-compose.simple.yml up --build -d
echo    2. Check status:  docker-compose -f docker-compose.simple.yml ps
echo    3. Access API:    curl http://localhost:8000/health
echo.
echo 🎉 Setup complete! Your KRAI Engine is ready to start.
pause
