#!/bin/bash

# KRAI Engine Docker Setup Script
# Generates secure passwords and creates .env file automatically

set -e

echo "🚀 KRAI Engine Docker Setup"
echo "============================"

# Function to generate secure random password
generate_password() {
    openssl rand -base64 32 | tr -d "=+/" | cut -c1-25
}

# Generate secure passwords
echo "🔐 Generating secure passwords..."
DB_PASSWORD=$(generate_password)
MINIO_SECRET_KEY=$(generate_password)

# Create .env file with generated passwords
echo "📝 Creating .env file with generated credentials..."

cat > .env << EOF
# KRAI Engine Environment Configuration
# Auto-generated by setup.sh on $(date)

# Application Settings
ENV=production
API_HOST=0.0.0.0
API_PORT=8000
LOG_LEVEL=DEBUG

# Database Configuration (PostgreSQL)
DATABASE_TYPE=postgresql
DATABASE_HOST=krai-postgres
DATABASE_PORT=5432
DATABASE_NAME=krai
DATABASE_USER=krai_user
DATABASE_PASSWORD=${DB_PASSWORD}

# Object Storage Configuration (MinIO)
OBJECT_STORAGE_TYPE=s3
OBJECT_STORAGE_ENDPOINT=http://krai-minio:9000
OBJECT_STORAGE_ACCESS_KEY=minioadmin
OBJECT_STORAGE_SECRET_KEY=${MINIO_SECRET_KEY}
OBJECT_STORAGE_REGION=us-east-1
OBJECT_STORAGE_USE_SSL=false
OBJECT_STORAGE_PUBLIC_URL=http://localhost:9000

# AI Service Configuration (Ollama)
AI_SERVICE_TYPE=ollama
AI_SERVICE_URL=http://krai-ollama:11434
EOF

# Make script executable
chmod 600 .env

echo "✅ .env file created successfully!"
echo ""
echo "🔑 Generated Credentials:"
echo "   Database Password: ${DB_PASSWORD}"
echo "   MinIO Secret Key:  ${MINIO_SECRET_KEY}"
echo ""
echo "📋 Next Steps:"
echo "   1. Start Docker: docker-compose -f docker-compose.simple.yml up --build -d"
echo "   2. Check status:  docker-compose -f docker-compose.simple.yml ps"
echo "   3. Access API:    curl http://localhost:8000/health"
echo ""
echo "🎉 Setup complete! Your KRAI Engine is ready to start."
