"""Embedding quality tests for deterministic mock embeddings.

These tests validate basic similarity behaviour, variance, and value
distribution for embeddings generated by the mock embedding service.
"""

from __future__ import annotations

from typing import List

import pytest


pytestmark = [pytest.mark.processor, pytest.mark.embedding, pytest.mark.embedding_quality]


class TestEmbeddingSimilarity:
    """Cosine-similarity based checks for mock embeddings."""

    def test_self_similarity_is_high(self, embedding_quality_metrics, sample_embeddings) -> None:
        """Vector compared with itself should have cosine similarity ≈ 1.0."""

        first = sample_embeddings[0]["embedding"]
        sim = embedding_quality_metrics.cosine_similarity(first, first)
        assert sim == pytest.approx(1.0, rel=1e-5, abs=1e-5)

    def test_similar_texts_are_closer_than_unrelated(self, embedding_quality_metrics, sample_embeddings) -> None:
        """Two paper-jam chunks should be closer than jam vs network config."""

        jam_vectors: List[List[float]] = []
        network_vectors: List[List[float]] = []

        for item in sample_embeddings:
            text = item["content"].lower()
            if "paper jam" in text or "13.a1.b2" in text:
                jam_vectors.append(item["embedding"])
            if "network configuration" in text:
                network_vectors.append(item["embedding"])

        # Sanity: we expect at least one vector in each group
        assert jam_vectors and network_vectors

        jam0 = jam_vectors[0]
        jam1 = jam_vectors[1] if len(jam_vectors) > 1 else jam_vectors[0]
        net0 = network_vectors[0]

        sim_jam = embedding_quality_metrics.cosine_similarity(jam0, jam1)
        sim_mixed = embedding_quality_metrics.cosine_similarity(jam0, net0)

        assert sim_jam > sim_mixed


class TestEmbeddingVariance:
    """Distribution checks for sets of embeddings."""

    def test_variance_is_positive_for_diverse_texts(self, embedding_quality_metrics, sample_embeddings) -> None:
        """Variance across multiple embeddings should be > 0 for diverse inputs."""

        vectors = [item["embedding"] for item in sample_embeddings[:10]]
        var = embedding_quality_metrics.calculate_embedding_variance(vectors)
        assert var > 0.0


class TestEmbeddingValueSanity:
    """Guard against NaN/Inf or extreme values in embeddings."""

    def test_all_values_within_reasonable_range(self, embedding_quality_metrics, sample_embeddings) -> None:
        """check_embedding_distribution should accept all mock embeddings."""

        for item in sample_embeddings[:20]:
            vec = item["embedding"]
            assert embedding_quality_metrics.check_embedding_distribution(vec) is True

