"""Pydantic models for image management APIs."""
from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, HttpUrl, PositiveInt, model_validator

from backend.models.document import DocumentResponse, SortOrder


class ImageType(str, Enum):
    """Enumerates supported semantic image types."""

    DIAGRAM = "diagram"
    PHOTO = "photo"
    SCREENSHOT = "screenshot"
    CHART = "chart"
    TABLE = "table"
    ILLUSTRATION = "illustration"
    LOGO = "logo"
    OTHER = "other"


class ImageFormat(str, Enum):
    """Enumerates supported raster/vector image formats."""

    PNG = "png"
    JPG = "jpg"
    JPEG = "jpeg"
    GIF = "gif"
    WEBP = "webp"
    SVG = "svg"
    BMP = "bmp"


class BucketType(str, Enum):
    """Enumerates supported R2 bucket categories."""

    DOCUMENT_IMAGES = "document_images"
    ERROR_IMAGES = "error_images"
    PARTS_IMAGES = "parts_images"


class ImageBase(BaseModel):
    """Shared attributes across create/update payloads."""

    document_id: Optional[str] = Field(None, description="Associated document identifier.")
    chunk_id: Optional[str] = Field(None, description="Associated chunk identifier.")
    filename: Optional[str] = Field(None, description="Internal filename stored in R2.")
    original_filename: Optional[str] = Field(None, description="Original uploaded filename.")
    storage_path: Optional[str] = Field(None, description="Relative storage path inside the bucket.")
    storage_url: Optional[HttpUrl] = Field(None, description="Public URL to access the image.")
    file_size: Optional[int] = Field(None, ge=0, description="File size in bytes.")
    image_format: Optional[ImageFormat] = Field(None, description="Image format/extension.")
    width_px: Optional[int] = Field(None, ge=0, description="Image width in pixels.")
    height_px: Optional[int] = Field(None, ge=0, description="Image height in pixels.")
    page_number: Optional[int] = Field(None, ge=0)
    image_index: Optional[int] = Field(None, ge=0, description="Index on the page if multiple images exist.")
    image_type: Optional[ImageType] = Field(None, description="Categorisation of the image content.")
    ai_description: Optional[str] = Field(
        None, description="Description generated by AI-based analysis."
    )
    ai_confidence: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Confidence score for AI-generated description."
    )
    contains_text: Optional[bool] = Field(
        None, description="Whether the image contains detected textual content."
    )
    ocr_text: Optional[str] = Field(
        None, description="Text extracted by OCR processing, if available."
    )
    ocr_confidence: Optional[float] = Field(
        None, ge=0.0, le=1.0, description="Confidence score for OCR extraction."
    )
    manual_description: Optional[str] = Field(
        None, description="Manually curated description for the image."
    )
    tags: Optional[List[str]] = Field(
        None, description="List of descriptive tags for categorisation."
    )
    file_hash: Optional[str] = Field(
        None, description="SHA-256 hash used for deduplication." ""
    )
    figure_number: Optional[str] = Field(
        None, description="Figure reference number from the source document."
    )
    figure_context: Optional[str] = Field(
        None, description="Additional context or captions related to the figure."
    )

    model_config = ConfigDict(from_attributes=True)


class ImageCreateRequest(ImageBase):
    """Payload for creating a new image metadata entry."""

    storage_url: HttpUrl = Field(..., description="Public URL for the stored image.")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "storage_url": "https://cdn.example.com/images/fuser-diagram.png",
                "document_id": "doc-123",
                "page_number": 12,
                "image_type": "diagram",
                "file_hash": "abc123...",
            }
        }
    )


class ImageUpdateRequest(ImageBase):
    """Payload for updating existing image metadata."""

    storage_url: Optional[HttpUrl] = Field(None)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "ai_description": "Updated AI description after reprocessing.",
                "image_type": "chart",
                "tags": ["statistics", "performance"],
            }
        }
    )


class ImageFilterParams(BaseModel):
    """Filtering options for listing images."""

    document_id: Optional[str] = None
    chunk_id: Optional[str] = None
    page_number: Optional[int] = Field(None, ge=0)
    image_type: Optional[ImageType] = None
    contains_text: Optional[bool] = None
    file_hash: Optional[str] = None
    search: Optional[str] = Field(
        None,
        description="Full-text search across filename, ai_description, manual_description, ocr_text.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "document_id": "doc-123",
                "page_number": 12,
                "image_type": "diagram",
                "contains_text": True,
                "search": "fuser assembly",
            }
        }
    )


class ImageSortParams(BaseModel):
    """Sorting configuration for image listings."""

    sort_by: str = Field(
        "created_at",
        description="Column to sort by (created_at, page_number, image_type, etc.).",
    )
    sort_order: SortOrder = Field(SortOrder.DESC, description="Sorting direction.")


class ImageResponse(ImageBase):
    """Represents an image metadata record."""

    id: str = Field(..., description="Unique identifier for the image record.")
    storage_url: HttpUrl = Field(...)
    created_at: Optional[str] = Field(None)
    updated_at: Optional[str] = Field(None)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "img-123",
                "storage_url": "https://cdn.example.com/images/fuser-diagram.png",
                "document_id": "doc-123",
                "page_number": 12,
                "image_type": "diagram",
                "contains_text": False,
                "created_at": "2024-10-05T12:34:56Z",
            }
        }
    )


class ChunkSnippet(BaseModel):
    """Chunk context response."""

    text_chunk: Optional[str] = Field(None, description="Extracted textual content from chunk.")
    page_start: Optional[int] = Field(None, ge=0)
    page_end: Optional[int] = Field(None, ge=0)

    model_config = ConfigDict(from_attributes=True)


class ImageWithRelationsResponse(ImageResponse):
    """Image response enriched with related entities."""

    document: Optional[DocumentResponse] = Field(None)
    chunk: Optional[ChunkSnippet] = Field(None)


class ImageListResponse(BaseModel):
    """Paginated image listing."""

    images: List[ImageResponse] = Field(...)
    total: int = Field(..., ge=0)
    page: int = Field(..., ge=1)
    page_size: int = Field(..., ge=1)
    total_pages: int = Field(..., ge=1)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "images": [
                    {
                        "id": "img-123",
                        "storage_url": "https://cdn.example.com/images/fuser-diagram.png",
                    }
                ],
                "total": 1,
                "page": 1,
                "page_size": 25,
                "total_pages": 1,
            }
        }
    )


class ImageUploadResponse(BaseModel):
    """Response payload for image upload operations."""

    success: bool = Field(...)
    image_id: Optional[str] = Field(None)
    storage_url: Optional[HttpUrl] = Field(None)
    storage_path: Optional[str] = Field(None)
    file_hash: Optional[str] = Field(None)
    file_size: Optional[int] = Field(None, ge=0)
    is_duplicate: bool = Field(...)
    bucket: Optional[str] = Field(None)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "success": True,
                "image_id": "img-123",
                "storage_url": "https://cdn.example.com/images/fuser-diagram.png",
                "storage_path": "documents/img-123.png",
                "file_hash": "abc123",
                "file_size": 204800,
                "is_duplicate": False,
                "bucket": "document_images",
            }
        }
    )


class ImageStatsResponse(BaseModel):
    """Aggregated statistics for images."""

    total_images: int = Field(..., ge=0)
    by_type: Dict[str, int] = Field(default_factory=dict)
    by_document: Dict[str, int] = Field(default_factory=dict)
    with_ocr_text: int = Field(..., ge=0)
    with_ai_description: int = Field(..., ge=0)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "total_images": 150,
                "by_type": {"diagram": 40, "photo": 60},
                "by_document": {"doc-123": 10, "doc-456": 5},
                "with_ocr_text": 80,
                "with_ai_description": 65,
            }
        }
    )
