#!/usr/bin/env python3
"""
Lexmark Subtitle Indexer
=========================

Downloads VTT subtitle files (EN + DE) for every Lexmark support video that
was scraped, converts the cue text to clean paragraphs, and stores them as
searchable chunks in krai_intelligence.chunks.

Flow per video
--------------
1. Read video rows that have metadata->tracks with srclang 'en' or 'de'
2. Download the VTT file via aiohttp
3. Parse VTT → clean text (strips timestamps / cue numbers)
4. Ensure a virtual "support video collection" document exists per model
   (krai_core.documents  document_type='support_video_collection')
5. Insert chunk(s) into krai_intelligence.chunks
6. Update krai_content.videos.related_chunks[] with the new chunk IDs
7. Embeddings are generated by the existing EmbeddingProcessor (separate run)

Usage
-----
    python scripts/index_lexmark_subtitles.py                  # all
    python scripts/index_lexmark_subtitles.py --limit 50       # first 50 videos
    python scripts/index_lexmark_subtitles.py --langs en       # English only
    python scripts/index_lexmark_subtitles.py --dry-run        # no DB writes
    python scripts/index_lexmark_subtitles.py --force          # re-index already done
"""

import argparse
import asyncio
import hashlib
import json
import logging
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional
from urllib.parse import urljoin

import aiohttp

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from backend.processors.env_loader import load_all_env_files
from backend.services.database_factory import create_database_adapter

load_all_env_files(PROJECT_ROOT)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger("lexmark_subtitle_indexer")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

BASE_URL     = "https://support.lexmark.com"
HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/122.0.0.0 Safari/537.36"
    ),
}
TARGET_LANGS = {"en", "de"}   # override with --langs

# Map ISO 639-2 (3-letter) → ISO 639-1 (2-letter)
LANG_NORMALIZE = {
    "eng": "en", "deu": "de", "ger": "de", "fra": "fr", "fre": "fr",
    "spa": "es", "ita": "it", "por": "pt", "nld": "nl", "pol": "pl",
}

def normalize_lang(code: str) -> str:
    """Normalize 3-letter ISO 639-2 codes to 2-letter ISO 639-1."""
    code = code.strip().lower()
    return LANG_NORMALIZE.get(code, code)

MODEL_RE = re.compile(r"/video-details/([^/]+)/", re.IGNORECASE)


async def resolve_manufacturer_id(pool, name: str) -> Optional[str]:
    """Look up manufacturer UUID by name (case-insensitive)."""
    async with pool.acquire() as conn:
        row = await conn.fetchval(
            "SELECT id FROM krai_core.manufacturers WHERE LOWER(name) = LOWER($1) LIMIT 1",
            name,
        )
    return str(row) if row else None

# ---------------------------------------------------------------------------
# VTT parser
# ---------------------------------------------------------------------------

_VTT_TIMESTAMP = re.compile(r"\d{2}:\d{2}:\d{2}[.,]\d{3}\s*-->\s*\d{2}:\d{2}:\d{2}[.,]\d{3}")
_VTT_CUE_ID   = re.compile(r"^\d+\s*$")
_HTML_TAG      = re.compile(r"<[^>]+>")


def parse_vtt(vtt_text: str) -> str:
    """Extract clean spoken text from a WebVTT file."""
    lines = vtt_text.splitlines()
    cue_lines: List[str] = []
    in_cue = False

    for line in lines:
        line = line.strip()
        if not line:
            in_cue = False
            continue
        if line.startswith("WEBVTT") or line.startswith("NOTE"):
            in_cue = False
            continue
        if _VTT_TIMESTAMP.search(line):
            in_cue = True
            continue
        if _VTT_CUE_ID.match(line):
            continue
        if in_cue:
            clean = _HTML_TAG.sub("", line).strip()
            if clean:
                cue_lines.append(clean)

    # Deduplicate consecutive identical lines (common in VTTs)
    deduped: List[str] = []
    prev = None
    for line in cue_lines:
        if line != prev:
            deduped.append(line)
            prev = line

    return " ".join(deduped).strip()


# ---------------------------------------------------------------------------
# DB helpers
# ---------------------------------------------------------------------------

async def load_videos_with_tracks(
    pool, schema_content: str, manufacturer_id: str, force: bool, limit: Optional[int], langs: set
) -> List[Dict]:
    """Return videos that have scraped tracks in the requested languages."""
    limit_clause = f"LIMIT {limit}" if limit else ""
    # Filter: has 'tracks' in metadata AND (force OR no subtitle chunk yet)
    force_clause = "" if force else "AND NOT (v.metadata ? 'subtitles_indexed')"
    query = f"""
        SELECT
            v.id,
            v.video_url,
            v.title,
            v.series_id,
            v.metadata AS metadata,
            p.model_number,
            p.id AS product_id
        FROM {schema_content}.videos v
        LEFT JOIN {schema_content}.video_products vp ON vp.video_id = v.id
        LEFT JOIN krai_core.products p ON p.id = vp.product_id
        WHERE v.manufacturer_id = $1::uuid
          AND v.metadata ? 'tracks'
          AND jsonb_array_length(v.metadata->'tracks') > 0
          {force_clause}
        ORDER BY v.created_at ASC
        {limit_clause}
    """
    async with pool.acquire() as conn:
        rows = await conn.fetch(query, manufacturer_id)

    results = []
    for row in rows:
        r = dict(row)
        metadata = r.get("metadata") or {}
        if isinstance(metadata, str):
            try:
                metadata = json.loads(metadata)
            except Exception:
                metadata = {}
        tracks = metadata.get("tracks", [])
        # Keep only tracks in requested languages
        filtered = [t for t in tracks if normalize_lang(t.get("srclang", "")) in langs]
        if filtered:
            r["tracks_filtered"] = filtered
            results.append(r)
    return results


async def get_or_create_virtual_document(
    pool, model_number: str, manufacturer_id: str, dry_run: bool
) -> str:
    """
    Return the document_id for the virtual 'support video collection' document
    of a given model. Creates it if it doesn't exist.
    """
    filename = f"lexmark_{model_number}_support_videos.virtual"

    async with pool.acquire() as conn:
        existing = await conn.fetchval(
            "SELECT id FROM krai_core.documents WHERE filename = $1 LIMIT 1",
            filename,
        )
        if existing:
            return str(existing)

        if dry_run:
            return f"dry-run-doc-{model_number}"

        doc_id = await conn.fetchval(
            """
            INSERT INTO krai_core.documents
                (filename, document_type, language, processing_status,
                 manufacturer, manufacturer_id, extracted_metadata)
            VALUES ($1, 'support_video_collection', 'multi', 'completed',
                    'Lexmark', $2::uuid, $3::jsonb)
            RETURNING id
            """,
            filename,
            manufacturer_id,
            json.dumps({"model_number": model_number, "source": "lexmark_support_videos"}),
        )
        logger.debug("Created virtual document for %s: %s", model_number, doc_id)
        return str(doc_id)


async def upsert_chunk(
    pool,
    schema_intel: str,
    document_id: str,
    chunk_index: int,
    text: str,
    language: str,
    video_id: str,
    video_url: str,
    model_number: str,
    dry_run: bool,
) -> Optional[str]:
    """Insert or update a subtitle chunk. Returns chunk_id."""
    fingerprint = hashlib.sha256(f"{document_id}:{language}:{text}".encode()).hexdigest()[:32]

    if dry_run:
        return f"dry-run-chunk-{fingerprint[:8]}"

    async with pool.acquire() as conn:
        chunk_id = await conn.fetchval(
            f"""
            INSERT INTO {schema_intel}.chunks
                (document_id, text_chunk, chunk_index, fingerprint,
                 processing_status, metadata)
            VALUES ($1::uuid, $2, $3, $4, 'pending', $5::jsonb)
            ON CONFLICT (fingerprint) DO NOTHING
            RETURNING id
            """,
            document_id,
            text,
            chunk_index,
            fingerprint,
            json.dumps({
                "chunk_type":   "video_subtitle",
                "language":     language,
                "video_id":     video_id,
                "video_url":    video_url,
                "model_number": model_number,
                "source":       "lexmark_support",
            }),
        )
        if chunk_id:
            return str(chunk_id)
        # Already exists — return existing id
        existing = await conn.fetchval(
            f"SELECT id FROM {schema_intel}.chunks WHERE fingerprint = $1 LIMIT 1",
            fingerprint,
        )
        return str(existing) if existing else None


async def update_video_chunks(
    pool, schema_content: str, video_id: str, chunk_ids: List[str], dry_run: bool
) -> None:
    """Append chunk_ids to videos.related_chunks and mark subtitles_indexed."""
    if dry_run or not chunk_ids:
        return

    async with pool.acquire() as conn:
        # Merge into existing related_chunks array (avoid duplicates)
        await conn.execute(
            f"""
            UPDATE {schema_content}.videos
            SET
                related_chunks = (
                    SELECT ARRAY(
                        SELECT DISTINCT unnest(
                            COALESCE(related_chunks, ARRAY[]::uuid[]) ||
                            $2::uuid[]
                        )
                    )
                ),
                metadata = COALESCE(metadata, '{{}}'::jsonb)
                           || jsonb_build_object('subtitles_indexed', true),
                updated_at = NOW()
            WHERE id = $1::uuid
            """,
            video_id,
            chunk_ids,
        )


# ---------------------------------------------------------------------------
# Download + index one video
# ---------------------------------------------------------------------------

async def process_video(
    session:    aiohttp.ClientSession,
    semaphore:  asyncio.Semaphore,
    pool,
    schema_content: str,
    schema_intel:   str,
    video:          Dict,
    dry_run:        bool,
) -> Dict:
    video_id     = str(video["id"])
    video_url    = video.get("video_url", "")
    model_number = video.get("model_number") or "Unknown"
    tracks       = video.get("tracks_filtered", [])

    result = {"video_id": video_id, "chunks_created": 0, "errors": []}

    # Get or create virtual document for this model
    doc_id = await get_or_create_virtual_document(pool, model_number, LEXMARK_ID, dry_run)

    chunk_ids: List[str] = []
    chunk_index = 0

    async with semaphore:
        for track in tracks:
            lang = normalize_lang(track.get("srclang", ""))
            vtt_url = track.get("src", "")
            if not vtt_url:
                continue

            try:
                async with session.get(vtt_url, timeout=aiohttp.ClientTimeout(total=15)) as resp:
                    if resp.status != 200:
                        result["errors"].append(f"HTTP {resp.status} for {vtt_url}")
                        continue
                    vtt_text = await resp.text(encoding="utf-8", errors="replace")

                clean_text = parse_vtt(vtt_text)
                if not clean_text or len(clean_text) < 10:
                    result["errors"].append(f"Empty VTT for {lang}: {vtt_url}")
                    continue

                chunk_id = await upsert_chunk(
                    pool, schema_intel,
                    document_id=doc_id,
                    chunk_index=chunk_index,
                    text=clean_text,
                    language=lang,
                    video_id=video_id,
                    video_url=video_url,
                    model_number=model_number,
                    dry_run=dry_run,
                )
                if chunk_id:
                    chunk_ids.append(chunk_id)
                    result["chunks_created"] += 1
                    chunk_index += 1

            except asyncio.TimeoutError:
                result["errors"].append(f"Timeout: {vtt_url}")
            except Exception as exc:
                import traceback
                result["errors"].append(f"Error {lang}: {exc} | {traceback.format_exc().splitlines()[-3]}")

    if chunk_ids:
        await update_video_chunks(pool, schema_content, video_id, chunk_ids, dry_run)

    return result


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

async def main(limit: Optional[int], concurrency: int, langs: set, force: bool, dry_run: bool) -> None:
    logger.info("=" * 60)
    logger.info("Lexmark Subtitle Indexer")
    logger.info("Sprachen: %s", ", ".join(sorted(langs)))
    if dry_run:
        logger.info("DRY RUN – keine DB-Änderungen")
    logger.info("=" * 60)

    db   = create_database_adapter()
    await db.connect()
    pool = db._ensure_pool()

    try:
        # Resolve manufacturer ID at runtime
        lexmark_id = await resolve_manufacturer_id(pool, "Lexmark")
        if not lexmark_id:
            logger.error("Manufacturer 'Lexmark' not found in database.")
            return

        videos = await load_videos_with_tracks(
            pool, db._content_schema, lexmark_id, force, limit, langs
        )
        logger.info("Videos mit passenden Untertiteln: %d", len(videos))

        if not videos:
            logger.info("Nichts zu tun.")
            return

        stats = {"chunks_created": 0, "videos_processed": 0, "errors": 0}
        semaphore = asyncio.Semaphore(concurrency)

        connector = aiohttp.TCPConnector(limit=concurrency, ssl=False)
        async with aiohttp.ClientSession(headers=HEADERS, connector=connector) as session:

            chunk_size = 50
            for start in range(0, len(videos), chunk_size):
                batch = videos[start : start + chunk_size]
                tasks = [
                    process_video(session, semaphore, pool,
                                  db._content_schema, db._intelligence_schema,
                                  v, dry_run)
                    for v in batch
                ]
                results = await asyncio.gather(*tasks)

                for res in results:
                    stats["chunks_created"]  += res["chunks_created"]
                    stats["videos_processed"] += 1
                    if res["errors"]:
                        stats["errors"] += len(res["errors"])
                        for e in res["errors"]:
                            logger.warning("  Video %s: %s", res["video_id"][:8], e)

                done = min(start + chunk_size, len(videos))
                logger.info(
                    "Fortschritt: %d / %d  (chunks=%d, fehler=%d)",
                    done, len(videos), stats["chunks_created"], stats["errors"],
                )
                if start + chunk_size < len(videos):
                    await asyncio.sleep(0.3)

        logger.info("=" * 60)
        logger.info("Ergebnis")
        logger.info("  Videos verarbeitet : %d", stats["videos_processed"])
        logger.info("  Chunks erstellt    : %d", stats["chunks_created"])
        logger.info("  Fehler/leere VTTs  : %d", stats["errors"])
        logger.info("=" * 60)
        logger.info("  ℹ️  Embeddings noch ausstehend.")
        logger.info("     Ausführen: python scripts/embed_lexmark_chunks.py")

    finally:
        await db.disconnect()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Index Lexmark video subtitles (VTT) as searchable chunks"
    )
    parser.add_argument("--limit",       type=int,   default=None,
                        help="Max. Anzahl Videos (Standard: alle)")
    parser.add_argument("--concurrency", type=int,   default=8,
                        help="Parallele Downloads (Standard: 8)")
    parser.add_argument("--langs",       type=str,   default="en,de",
                        help="Komma-getrennte Sprachen (Standard: en,de)")
    parser.add_argument("--force",       action="store_true",
                        help="Bereits indexierte Videos neu verarbeiten")
    parser.add_argument("--dry-run",     action="store_true",
                        help="Nur testen, keine DB-Änderungen")
    args = parser.parse_args()

    selected_langs = {l.strip().lower() for l in args.langs.split(",")}
    asyncio.run(main(args.limit, args.concurrency, selected_langs, args.force, args.dry_run))
