# Epson Product Configuration

manufacturer:
  canonical_name: "Epson"
  aliases: ["epson", "Epson", "EPSON", "Seiko Epson"]

product_patterns:
  - pattern: '\b(?:WorkForce|EcoTank)\s+[A-Z]{2,3}-\d{3,4}\b'
    flags: IGNORECASE
    examples: ["WorkForce Pro WF-C5790", "EcoTank ET-4760"]
    series: "WorkForce"
    type: "inkjet_multifunction"

series:
  - name: "WorkForce"
    patterns: ["WorkForce"]
    type: "inkjet_multifunction"
  - name: "EcoTank"
    patterns: ["EcoTank"]
    type: "inkjet_multifunction"

part_prefixes:
  - prefix: "T"
    type: "ink_cartridge"
    pattern: "^T\\d{3,4}[A-Z]?$"
    examples: ["T676XL", "T802XL"]

reject_patterns:
  - pattern: ".*must be installed.*"
    reason: "Description text"
